export const mockMovies = [
  {
    Title: "Dune: Part Two",
    Year: "2024",
    Rated: "PG-13",
    Released: "01 Mar 2024",
    Runtime: "166 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Denis Villeneuve",
    Writer: "Denis Villeneuve, Jon Spaihts, Frank Herbert",
    Actors: "Timothée Chalamet, Zendaya, Rebecca Ferguson, Javier Bardem",
    Plot: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future only he can foresee.",
    Language: "English",
    Country: "United States, Canada",
    Awards: "Won 6 Oscars. 38 wins & 52 nominations total",
    Poster: "https://image.tmdb.org/t/p/w500/czemb42u5L6FWwJWI4hdqDOhC4b.jpg",
    Backdrop: "/dune_backdrop.png",
    Tagline: "Long live the fighters.",
    Metascore: "79",
    imdbRating: "8.6",
    imdbVotes: "430,221",
    imdbID: "tt15239678",
    Type: "movie"
  },
  {
    Title: "Inception",
    Year: "2010",
    Rated: "PG-13",
    Released: "16 Jul 2010",
    Runtime: "148 min",
    Genre: "Action, Adventure, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Christopher Nolan",
    Actors: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Ken Watanabe",
    Plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project.",
    Language: "English, Japanese, French",
    Country: "United States, United Kingdom",
    Awards: "Won 4 Oscars. 159 wins & 220 nominations total",
    Poster: "https://image.tmdb.org/t/p/w500/o07wJy5H6Z2j6N5Xz2n8rjypj2B.jpg",
    Backdrop: "https://image.tmdb.org/t/p/original/8Zg0n575w5p9kzwxQ93n8b2hP8p.jpg",
    Tagline: "Your mind is the scene of the crime.",
    Metascore: "74",
    imdbRating: "8.8",
    imdbVotes: "2,548,102",
    imdbID: "tt1375666",
    Type: "movie"
  },
  {
    Title: "Interstellar",
    Year: "2014",
    Rated: "PG-13",
    Released: "07 Nov 2014",
    Runtime: "169 min",
    Genre: "Adventure, Drama, Sci-Fi",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan",
    Actors: "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Mackenzie Foy",
    Plot: "When Earth becomes uninhabitable, a team of explorers travels through a wormhole in space in an attempt to ensure humanity's survival by searching for a new home among the stars.",
    Language: "English",
    Country: "United States, United Kingdom, Canada",
    Awards: "Won 1 Oscar. 44 wins & 148 nominations total",
    Poster: "https://image.tmdb.org/t/p/w500/gEU2QvIPwc3hzv1872z74YcZzZs.jpg",
    Backdrop: "https://image.tmdb.org/t/p/original/rAiw16KOu8n66gSpki5qiPpQCuc.jpg",
    Tagline: "Mankind was born on Earth. It was never meant to die here.",
    Metascore: "74",
    imdbRating: "8.7",
    imdbVotes: "2,019,234",
    imdbID: "tt0816692",
    Type: "movie"
  },
  {
    Title: "The Dark Knight",
    Year: "2008",
    Rated: "PG-13",
    Released: "18 Jul 2008",
    Runtime: "152 min",
    Genre: "Action, Crime, Drama",
    Director: "Christopher Nolan",
    Writer: "Jonathan Nolan, Christopher Nolan, David S. Goyer",
    Actors: "Christian Bale, Heath Ledger, Aaron Eckhart, Maggie Gyllenhaal",
    Plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    Language: "English, Mandarin",
    Country: "United States, United Kingdom",
    Awards: "Won 2 Oscars. 163 wins & 160 nominations total",
    Poster: "https://image.tmdb.org/t/p/w500/qJ2tW65RNowTz58771IvW2fn7tr.jpg",
    Backdrop: "https://image.tmdb.org/t/p/original/nMK428pghs2y5uK2Z4w3n98tXp9.jpg",
    Tagline: "Why So Serious?",
    Metascore: "84",
    imdbRating: "9.0",
    imdbVotes: "2,892,109",
    imdbID: "tt0468569",
    Type: "movie"
  },
  {
    Title: "Spider-Man: Into the Spider-Verse",
    Year: "2018",
    Rated: "PG",
    Released: "14 Dec 2018",
    Runtime: "117 min",
    Genre: "Animation, Action, Adventure",
    Director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
    Writer: "Phil Lord, Rodney Rothman",
    Actors: "Shameik Moore, Jake Johnson, Hailee Steinfeld, Mahershala Ali",
    Plot: "Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions to stop a threat that could destroy all realities.",
    Language: "English, Spanish",
    Country: "United States",
    Awards: "Won 1 Oscar. 87 wins & 59 nominations total",
    Poster: "https://image.tmdb.org/t/p/w500/iiJy61hp0Qr2qgO6k7n4n656eao.jpg",
    Backdrop: "https://image.tmdb.org/t/p/original/785m31gS23T3YV8yM3N671b56.jpg",
    Tagline: "More than one wears the mask.",
    Metascore: "87",
    imdbRating: "8.4",
    imdbVotes: "640,119",
    imdbID: "tt4633694",
    Type: "movie"
  },
  {
    Title: "Parasite",
    Year: "2019",
    Rated: "R",
    Released: "30 May 2019",
    Runtime: "132 min",
    Genre: "Drama, Thriller",
    Director: "Bong Joon Ho",
    Writer: "Bong Joon Ho, Han Jin Won",
    Actors: "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik",
    Plot: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan, culminating in a shocking explosion of violence.",
    Language: "Korean, English",
    Country: "South Korea",
    Awards: "Won 4 Oscars. 308 wins & 271 nominations total",
    Poster: "https://image.tmdb.org/t/p/w500/7IiTTjVFXZ1j7v7nBNEZ2yabHyz.jpg",
    Backdrop: "https://image.tmdb.org/t/p/original/hi64r4c0x3WJqN4zJ4j7yWc8D4P.jpg",
    Tagline: "Act like you own the place.",
    Metascore: "96",
    imdbRating: "8.5",
    imdbVotes: "931,202",
    imdbID: "tt6751668",
    Type: "movie"
  },
  {
    Title: "Stranger Things",
    Year: "2016–2025",
    Rated: "TV-14",
    Released: "15 Jul 2016",
    Runtime: "51 min",
    Genre: "Drama, Fantasy, Horror",
    Director: "N/A",
    Writer: "Matt Duffer, Ross Duffer",
    Actors: "Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour",
    Plot: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl with telekinetic powers.",
    Language: "English",
    Country: "United States",
    Awards: "Nominated for 4 Golden Globes. 110 wins & 298 nominations total",
    Poster: "https://image.tmdb.org/t/p/w500/x2LSRK2CmHNnIISzvIE3Rev87vx.jpg",
    Backdrop: "https://image.tmdb.org/t/p/original/56v2Kj0UE72z42uXn6ui0Hb75qc.jpg",
    Tagline: "One summer can change everything.",
    Metascore: "N/A",
    imdbRating: "8.7",
    imdbVotes: "1,310,245",
    imdbID: "tt5074352",
    Type: "series"
  },
  {
    Title: "Breaking Bad",
    Year: "2008–2013",
    Rated: "TV-MA",
    Released: "20 Jan 2008",
    Runtime: "49 min",
    Genre: "Crime, Drama, Thriller",
    Director: "N/A",
    Writer: "Vince Gilligan",
    Actors: "Bryan Cranston, Aaron Paul, Anna Gunn, Betsy Brandt",
    Plot: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.",
    Language: "English, Spanish",
    Country: "United States",
    Awards: "Won 16 Primetime Emmys. 154 wins & 247 nominations total",
    Poster: "https://image.tmdb.org/t/p/w500/ztkUQv63Mz4836Jj2nuaXmq95En.jpg",
    Backdrop: "https://image.tmdb.org/t/p/original/tsRy63MuTJClv36CY55A1LdnLVw.jpg",
    Tagline: "Remember my name.",
    Metascore: "N/A",
    imdbRating: "9.5",
    imdbVotes: "2,190,523",
    imdbID: "tt0903747",
    Type: "series"
  }
];
